// REACT
import { StyleSheet } from 'react-native';

// THEMES
import { ThemeType } from 'src/theme/themes';

// CONSTANTS
import { styleConstants } from 'src/styles/style-constants';

export const getCommonStyles = (theme: ThemeType) =>
    StyleSheet.create({
        // FLEX
        row: { flexDirection: 'row' },

        // POSITIONS
        relative: { position: 'relative' },
        absolute: { position: 'absolute' },

        // ALIGNMENTS
        ai_baseline: { alignItems: 'baseline' },
        ai_center: { alignItems: 'center' },
        ai_end: { alignItems: 'flex-end' },
        ai_start: { alignItems: 'flex-start' },
        ai_stretch: { alignItems: 'stretch' },

        jc_center: { justifyContent: 'center' },
        jc_end: { justifyContent: 'flex-end' },
        jc_start: { justifyContent: 'flex-start' },
        jc_around: { justifyContent: 'space-around' },
        jc_between: { justifyContent: 'space-between' },
        jc_evenly: { justifyContent: 'space-evenly' },

        // WIDTHS
        w_screenLimit: { maxWidth: styleConstants.screenWidthLimitWithMainPadding },
        w_100: { width: styleConstants.percent100 },
        w_90: { width: styleConstants.percent90 },
        w_80: { width: styleConstants.percent80 },
        w_75: { width: styleConstants.percent75 },
        w_70: { width: styleConstants.percent70 },
        w_60: { width: styleConstants.percent60 },
        w_50: { width: styleConstants.percent50 },
        w_40: { width: styleConstants.percent40 },
        w_33: { width: styleConstants.percent33 },
        w_30: { width: styleConstants.percent30 },
        w_25: { width: styleConstants.percent25 },
        w_20: { width: styleConstants.percent20 },
        w_15: { width: styleConstants.percent15 },
        w_12_5: { width: styleConstants.percent12_5 },
        w_10: { width: styleConstants.percent10 },
        w_5: { width: styleConstants.percent5 },

        // HEIGHTS
        h_100: { height: styleConstants.percent100 },
        h_90: { height: styleConstants.percent90 },
        h_80: { height: styleConstants.percent80 },
        h_75: { height: styleConstants.percent75 },
        h_70: { height: styleConstants.percent70 },
        h_60: { height: styleConstants.percent60 },
        h_50: { height: styleConstants.percent50 },
        h_40: { height: styleConstants.percent40 },
        h_33: { height: styleConstants.percent33 },
        h_30: { height: styleConstants.percent30 },
        h_25: { height: styleConstants.percent25 },
        h_20: { height: styleConstants.percent20 },
        h_15: { height: styleConstants.percent15 },
        h_12_5: { height: styleConstants.percent12_5 },
        h_10: { height: styleConstants.percent10 },
        h_5: { height: styleConstants.percent5 },

        // TEXTS
        title: {
            fontSize: styleConstants.fontSizeLG,
            fontWeight: 'bold'
        },
        text_xs: { fontSize: styleConstants.fontSizeXS },
        text_sm: { fontSize: styleConstants.fontSizeSM },
        text_md: { fontSize: styleConstants.fontSizeMD },
        text_lg: { fontSize: styleConstants.fontSizeLG },
        text_xl: { fontSize: styleConstants.fontSizeXL },
        text_2xl: { fontSize: styleConstants.fontSize2XL },

        text_left: { textAlign: 'left' },
        text_center: { textAlign: 'center' },
        text_right: { textAlign: 'right' },
        text_bold: { fontWeight: 'bold' },

        text_primary: { color: theme.primaryText },
        text_grey: { color: theme.secondaryText },
        text_error: { color: theme.deleteRed },
        text_clickable: { color: theme.clickableBlueText },

        // BORDERS
        bw_xs: { borderWidth: styleConstants.borderXS },
        bw_sm: { borderWidth: styleConstants.borderSM },
        bw_md: { borderWidth: styleConstants.borderMD },
        bw_lg: { borderWidth: styleConstants.borderLG },
        bw_xl: { borderWidth: styleConstants.borderXL },
        bwt_xs: { borderTopWidth: styleConstants.borderXS },
        bwt_sm: { borderTopWidth: styleConstants.borderSM },
        bwt_md: { borderTopWidth: styleConstants.borderMD },
        bwt_lg: { borderTopWidth: styleConstants.borderLG },
        bwt_xl: { borderTopWidth: styleConstants.borderXL },
        bwr_xs: { borderRightWidth: styleConstants.borderXS },
        bwr_sm: { borderRightWidth: styleConstants.borderSM },
        bwr_md: { borderRightWidth: styleConstants.borderMD },
        bwr_lg: { borderRightWidth: styleConstants.borderLG },
        bwr_xl: { borderRightWidth: styleConstants.borderXL },
        bwb_xs: { borderBottomWidth: styleConstants.borderXS },
        bwb_sm: { borderBottomWidth: styleConstants.borderSM },
        bwb_md: { borderBottomWidth: styleConstants.borderMD },
        bwb_lg: { borderBottomWidth: styleConstants.borderLG },
        bwb_xl: { borderBottomWidth: styleConstants.borderXL },
        bwl_xs: { borderLeftWidth: styleConstants.borderXS },
        bwl_sm: { borderLeftWidth: styleConstants.borderSM },
        bwl_md: { borderLeftWidth: styleConstants.borderMD },
        bwl_lg: { borderLeftWidth: styleConstants.borderLG },
        bwl_xl: { borderLeftWidth: styleConstants.borderXL },

        // BORDER RADIUS
        br_xs: { borderRadius: styleConstants.borderRadiusXS },
        br_sm: { borderRadius: styleConstants.borderRadiusSM },
        br_md: { borderRadius: styleConstants.borderRadiusMD },
        br_lg: { borderRadius: styleConstants.borderRadiusLG },
        br_xl: { borderRadius: styleConstants.borderRadiusXL },
        brts_xs: { borderTopStartRadius: styleConstants.borderRadiusXS },
        brts_sm: { borderTopStartRadius: styleConstants.borderRadiusSM },
        brts_md: { borderTopStartRadius: styleConstants.borderRadiusMD },
        brts_lg: { borderTopStartRadius: styleConstants.borderRadiusLG },
        brts_xl: { borderTopStartRadius: styleConstants.borderRadiusXL },
        brte_xs: { borderTopEndRadius: styleConstants.borderRadiusXS },
        brte_sm: { borderTopEndRadius: styleConstants.borderRadiusSM },
        brte_md: { borderTopEndRadius: styleConstants.borderRadiusMD },
        brte_lg: { borderTopEndRadius: styleConstants.borderRadiusLG },
        brte_xl: { borderTopEndRadius: styleConstants.borderRadiusXL },
        brbs_xs: { borderBottomStartRadius: styleConstants.borderRadiusXS },
        brbs_sm: { borderBottomStartRadius: styleConstants.borderRadiusSM },
        brbs_md: { borderBottomStartRadius: styleConstants.borderRadiusMD },
        brbs_lg: { borderBottomStartRadius: styleConstants.borderRadiusLG },
        brbs_xl: { borderBottomStartRadius: styleConstants.borderRadiusXL },
        brbe_xs: { borderBottomEndRadius: styleConstants.borderRadiusXS },
        brbe_sm: { borderBottomEndRadius: styleConstants.borderRadiusSM },
        brbe_md: { borderBottomEndRadius: styleConstants.borderRadiusMD },
        brbe_lg: { borderBottomEndRadius: styleConstants.borderRadiusLG },
        brbe_xl: { borderBottomEndRadius: styleConstants.borderRadiusXL },
        br_circle: { borderRadius: styleConstants.borderRadiusCircle },

        // GAPS
        gap_xs: { gap: styleConstants.gapXS },
        gap_sm: { gap: styleConstants.gapSM },
        gap_md: { gap: styleConstants.gapMD },
        gap_lg: { gap: styleConstants.gapLG },
        gap_xl: { gap: styleConstants.gapXL },

        // MARGINS
        m_xs: { margin: styleConstants.marginXS },
        m_sm: { margin: styleConstants.marginSM },
        m_md: { margin: styleConstants.marginMD },
        m_lg: { margin: styleConstants.marginLG },
        m_xl: { margin: styleConstants.marginXL },
        mx_xs: { marginHorizontal: styleConstants.marginXS },
        mx_sm: { marginHorizontal: styleConstants.marginSM },
        mx_md: { marginHorizontal: styleConstants.marginMD },
        mx_lg: { marginHorizontal: styleConstants.marginLG },
        mx_xl: { marginHorizontal: styleConstants.marginXL },
        my_xs: { marginVertical: styleConstants.marginXS },
        my_sm: { marginVertical: styleConstants.marginSM },
        my_md: { marginVertical: styleConstants.marginMD },
        my_lg: { marginVertical: styleConstants.marginLG },
        my_xl: { marginVertical: styleConstants.marginXL },
        mt_xs: { marginTop: styleConstants.marginXS },
        mt_sm: { marginTop: styleConstants.marginSM },
        mt_md: { marginTop: styleConstants.marginMD },
        mt_lg: { marginTop: styleConstants.marginLG },
        mt_xl: { marginTop: styleConstants.marginXL },
        mr_xs: { marginRight: styleConstants.marginXS },
        mr_sm: { marginRight: styleConstants.marginSM },
        mr_md: { marginRight: styleConstants.marginMD },
        mr_lg: { marginRight: styleConstants.marginLG },
        mr_xl: { marginRight: styleConstants.marginXL },
        mb_xs: { marginBottom: styleConstants.marginXS },
        mb_sm: { marginBottom: styleConstants.marginSM },
        mb_md: { marginBottom: styleConstants.marginMD },
        mb_lg: { marginBottom: styleConstants.marginLG },
        mb_xl: { marginBottom: styleConstants.marginXL },
        ml_xs: { marginLeft: styleConstants.marginXS },
        ml_sm: { marginLeft: styleConstants.marginSM },
        ml_md: { marginLeft: styleConstants.marginMD },
        ml_lg: { marginLeft: styleConstants.marginLG },
        ml_xl: { marginLeft: styleConstants.marginXL },

        // PADDINGS
        p_xs: { padding: styleConstants.paddingXS },
        p_sm: { padding: styleConstants.paddingSM },
        p_md: { padding: styleConstants.paddingMD },
        p_lg: { padding: styleConstants.paddingLG },
        p_xl: { padding: styleConstants.paddingXL },
        px_xs: { paddingHorizontal: styleConstants.paddingXS },
        px_sm: { paddingHorizontal: styleConstants.paddingSM },
        px_md: { paddingHorizontal: styleConstants.paddingMD },
        px_lg: { paddingHorizontal: styleConstants.paddingLG },
        px_xl: { paddingHorizontal: styleConstants.paddingXL },
        py_xs: { paddingVertical: styleConstants.paddingXS },
        py_sm: { paddingVertical: styleConstants.paddingSM },
        py_md: { paddingVertical: styleConstants.paddingMD },
        py_lg: { paddingVertical: styleConstants.paddingLG },
        py_xl: { paddingVertical: styleConstants.paddingXL },
        pt_xs: { paddingTop: styleConstants.paddingXS },
        pt_sm: { paddingTop: styleConstants.paddingSM },
        pt_md: { paddingTop: styleConstants.paddingMD },
        pt_lg: { paddingTop: styleConstants.paddingLG },
        pt_xl: { paddingTop: styleConstants.paddingXL },
        pr_xs: { paddingRight: styleConstants.paddingXS },
        pr_sm: { paddingRight: styleConstants.paddingSM },
        pr_md: { paddingRight: styleConstants.paddingMD },
        pr_lg: { paddingRight: styleConstants.paddingLG },
        pr_xl: { paddingRight: styleConstants.paddingXL },
        pb_xs: { paddingBottom: styleConstants.paddingXS },
        pb_sm: { paddingBottom: styleConstants.paddingSM },
        pb_md: { paddingBottom: styleConstants.paddingMD },
        pb_lg: { paddingBottom: styleConstants.paddingLG },
        pb_xl: { paddingBottom: styleConstants.paddingXL },
        pl_xs: { paddingLeft: styleConstants.paddingXS },
        pl_sm: { paddingLeft: styleConstants.paddingSM },
        pl_md: { paddingLeft: styleConstants.paddingMD },
        pl_lg: { paddingLeft: styleConstants.paddingLG },
        pl_xl: { paddingLeft: styleConstants.paddingXL },
    });